### ISSUE TITLE
Sony Dualshock 4 controllers become non-functional.

### ISSUE THREAD

**Issue by Pieman492** [M0Rf30/android-udev-rules#250]
Operating System: Arch Linux

After half a year plus of having this issue, googling brought me to [this](https://www.reddit.com/r/wine_gaming/comments/10hssh2/dualshock_4_invisible_everywhere_outside_of_wine/) thread allowing me to narrow down the issue to these rules.

It appears to me that the likely culprit is the fact that Sony phones and Dualshock 4 controllers share a vendor ID. Removing the package makes this issue disappear.  

Apologies for not being able to provide a fix or more concrete information, but I don't actually know anything about udev so this is just what I've been able to piece together.

**Comment by M0Rf30** [comment]
Hi @Pieman492 can you send me the output of `udevadm info` ?
 - with installed rules
 - without
 
thanks

**Comment by JoesCat** [comment]
Looking for info, it appears we need several exclusions.
There are three here [3 devices](https://www.gamingonlinux.com/articles/you-will-need-to-update-your-udev-rules-for-the-steam-controller.8593/page=3/) and yet another device here [05c5 instead of 05c4 plus large list](https://gitlab.com/fabiscafe/game-devices-udev/-/blob/main/README.md) which has a large list that would be useful (for the numerical values).

The 5c4 and 5c5 could be combined as:
ATTRS{idVendor}=="054c", ATTRS{idProduct}=="05c?",GOTO="android_usb_rules_end"

**Comment by JoesCat** [comment]
Hi @Pieman492 - can you test this updated rule set?
You can find it here before it is merged into main code:
https://github.com/JoesCat/android-udev-rules/blob/dual/51-android.rules
This should exclude your Dualshock, but it would be great if you can confim this.

**Comment by Pieman492** [comment]
@M0Rf30 `udevadm info` outputs "A device name or path is required", and I wouldn't know which one to give it unfortunately.  On the other hand. . .
@JoesCat I can confirm that that while using the mainline causes the issue, these updated rules fix it completely and my controller continues to work.
