### ISSUE TITLE
0fce:0156 Xperia Neo V is detected as HID device

### ISSUE THREAD

**Issue by bjo81** [M0Rf30/android-udev-rules#50]
My Neo V with CM11 is running in MTP-mode, but detected as HID device with Kernel 3.18.2 and android-udev r124-1.

[  373.598520] usb 2-5: new high-speed USB device number 2 using ehci-pci
[  373.726593] input: Sony Ericsson MT11i as /devices/pci0000:00/0000:00:13.2/usb2/2-5/2-5:1.1/0003:0FCE:0156.0008/input/input16
[  373.727011] hid-generic 0003:0FCE:0156.0008: input,hidraw0: USB HID v1.01 Keyboard [Sony Ericsson MT11i] on usb-0000:00:13.2-5/input1
[  373.729265] input: Sony Ericsson MT11i as /devices/pci0000:00/0000:00:13.2/usb2/2-5/2-5:1.2/0003:0FCE:0156.0009/input/input17
[  373.729492] hid-generic 0003:0FCE:0156.0009: input,hidraw1: USB HID v1.01 Mouse [Sony Ericsson MT11i] on usb-0000:00:13.2-5/input2

**Comment by M0Rf30** [comment]
Have you installed libmtp? If not, install, reboot and let me know

**Comment by bjo81** [comment]
Sure, android-udev has libmtp as dependency on Arch.

**Comment by M0Rf30** [comment]
# SonyEricsson MT11i Xperia Neo MTP
ATTR{idVendor}=="0fce", ATTR{idProduct}=="0156", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"

this rule is written in mtp rules. You should contact the libmtp developers in order to isolate android rules from mtp ones. Please try some diagnostics reported here:
https://wiki.archlinux.org/index.php/MTP
